<?php

/**
 * PluginsfFlowNodeConnectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfFlowNodeConnectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfFlowNodeConnectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfFlowNodeConnection');
    }
}