<?php

/**
 * PluginsfFlowNodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfFlowNodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfFlowNodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfFlowNode');
    }
}