<?php

/**
 * PluginsfFlowStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfFlowStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfFlowStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfFlowState');
    }
}