<?php

/**
 * PluginsfFlowWorkflowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfFlowWorkflowTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfFlowWorkflowTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfFlowWorkflow');
    }
}